# Generated by Django 4.2.16 on 2025-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
