# Generated by Django 4.2.16 on 2025-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
