# Generated by Django 4.2.16 on 2025-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_document_alter_contract_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
