# Generated by Django 4.2.16 on 2025-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_contract_text_alter_contract_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
