# Generated by Django 4.2.16 on 2025-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_contract_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
